services:
  wiki:
    image: requarks/wiki:2
    environment:
      DB_TYPE: sqlite
      DB_FILEPATH: /wiki/database.sqlite
    
    ports:
      # <Host Port>:<Container Port>
      - "3000:3000"

    volumes:
      - ./data/database.sqlite:/wiki/database.sqlite
    restart: unless-stopped
